config/routes.rb
FacebookApp::Application.routes.draw do
  resources :users
  root to: 'home#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  resources :password_resets, only: [:new, :create, :edit, :update]
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'users/new'
  resources :posts do
    member do
      post 'vote'
    end
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  get 'friendships/create'
  get 'friendships/update'
  get 'friendships/destroy'
  resources :home
  resources :friendships, only: [:create, :update, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
  has_many :votes, as: :voteable

  def total_votes
    up_votes + down_votes
  end
  
  def up_votes
    votes.where(vote: true).size
  end
  
  def down_votes
    votes.where(vote: false).size
  end

  def already_upvoted?(user)
    vote = votes.find_by(user_id: user.id, vote: true)
    vote.present? ? true : false
  end

  def already_downvoted?(user)
    vote = votes.find_by(user_id: user.id, vote: false)
    vote.present? ? true : false
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit,
                                      :update, :comment_owner,
                                      :vote]
  before_action :comment_owner, only: [:destroy, :edit, :update]
  def create
    @comment = @post.comments.create(comment_params)
    if @comment.errors.present?
      flash[:alert] = "Comment #{@comment.errors[:content].first}"
      redirect_to post_path(@post)
    else
      @comment.user_id = current_user.id
      @comment.save
      if @comment.save
        redirect_to post_path(@post)
      end
    end
  end

  def edit
    
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def vote
    if !@comment.already_upvoted?(current_user) && params[:vote] == 'true'
      vote = Vote.find_by(voteable: @comment,
                          creator: current_user,
                          vote: false)
      if vote.present?
        vote.update_attributes(voteable: @comment,
                               creator: current_user,
                               vote: params[:vote])
      else
        Vote.create(voteable: @comment,
                    creator: current_user,
                    vote: params[:vote])
      end
    elsif !@comment.already_downvoted?(current_user) && params[:vote] == 'false'
      vote = Vote.find_by(voteable: @comment, creator: current_user, vote: true)
      if vote.present?
        vote.update_attributes(voteable: @comment,
                               creator: current_user,
                               vote: params[:vote])
      else
        Vote.create(voteable: @comment,
                    creator: current_user,
                    vote: params[:vote])
      end
    end
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:alert] = "That comment doesn't belong to you!"
      redirect_to @post
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.container
  .row
    %h2=pluralize(@comments.count, "Comment")
    - @comments.each do |comment|
      .col-sm-8
        .panel.panel-white.post.panel-shadow
          .post-heading
            .pull-left.image
              %img.img-circle.avatar{:alt => "user profile image", :src => "http://bootdey.com/img/Content/user_1.jpg"}/
            .pull-left.meta
              .title.h5
                %a{:href => "#"}
                  %b=comment.user.name
                made a comment.
              %h6.text-muted.time Posted #{time_ago_in_words(comment.created_at)} ago.
          .post-description
            %p=comment.content
            .stats
              %span.glyphicon.glyphicon-thumbs-up
              = link_to "Like", vote_post_comment_path(comment.post, comment, vote: true), method: 'post'
              %span.glyphicon.glyphicon-thumbs-down
              = link_to "Unlike", vote_post_comment_path(comment.post, comment, vote: false), method: 'post'
              -if current_user == comment.user
                =link_to 'Edit Comment', edit_post_comment_path(comment.post, comment), class: 'btn btn-default stat-item'
                =link_to 'Destroy Comment', [comment.post,comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default stat-item'
            %p
              %span.glyphicon.glyphicon-thumbs-up
              #{comment.up_votes}
              %span.glyphicon.glyphicon-thumbs-down
              #{comment.down_votes}
%link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
%script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
/ =render 'comments/form'

app/views/comments/_form.html.haml
.comment-form
  = form_for([@post, @post.comments.build], remote: true) do |f|
    = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{@post.id}"
    =f.submit

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/edit.html.haml
= form_for([@post, @comment]) do |f|
  =f.text_area :content
  =f.submit

app/views/comments/new.html.haml
%h1 Comments#new
%p Find me in app/views/comments/new.html.haml