config/routes.rb
FacebookApp::Application.routes.draw do
  resources :users
  root to: 'home#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  resources :password_resets, only: [:new, :create, :edit, :update]
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'users/new'
  resources :posts do
    member do
      post 'vote'
    end
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  get 'friendships/create'
  get 'friendships/update'
  get 'friendships/destroy'
  resources :home
  resources :friendships, only: [:create, :update, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    redirect_to '/login' unless current_user.present?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%nav.navbar.navbar-default
  .container-fluid.navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          .navbar-brand Welcome #{current_user.name}
          %li
            = link_to 'View Post', posts_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu

              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: "delete"
        - else
          %li= link_to "Log in", login_path, :method => :get
          %li= link_to "Sign Up", logout_path, :method => :get
.panel.panel-default
  .panel-heading Friends List:
  %table.table-hover.table-condensed
    - @users.each do |user|
      - if user != current_user && user.pending && !current_user.pending.include?(user) && !current_user.active_friends.include?(user) && !current_user.received_friends.include?(user)
        %tr
          %td= user.email
          %td= link_to "Add Friend", friendships_path(friend_id: user), method: :post

.panel.panel-default
  .panel-heading Your awaiting friend requests:
  %table.table-hover.table-condensed
    - current_user.requested_friendships.each do |request|
      -unless current_user.active_friends.include?(request)
        %tr
          %td= request.email
          %td= link_to "Accept",  friendship_path(id: request.id), method: "put"
          %td= link_to "Decline", friendship_path(id: request.id), method: :delete

.panel.panel-default
  .panel-heading Your sent friend requests:
  %table.table-hover.table-condensed
    - current_user.pending_friends.each do |request|
      %tr
        %td= request.email
        %td= link_to "Decline", friendship_path(id: request.id), method: :delete

.panel.panel-default
  .panel-heading Active users:
  %table.table-hover.table-condensed
    - current_user.active_friends.each do |request|
      %tr
        %td= request.email
        %td= link_to "Decline", friendship_path(id: request.id), method: :delete
    - current_user.received_friends.each do |request|
      %tr
        %td= request.email
        %td= link_to "Decline", friendship_path(id: request.id), method: :delete