config/routes.rb
FacebookApp::Application.routes.draw do
  resources :users
  root to: 'home#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  resources :password_resets, only: [:new, :create, :edit, :update]
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'users/new'
  resources :posts do
    member do
      post 'vote'
    end
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  get 'friendships/create'
  get 'friendships/update'
  get 'friendships/destroy'
  resources :home
  resources :friendships, only: [:create, :update, :destroy]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  has_many :votes, as: :voteable

  def total_votes
    up_votes + down_votes
  end
  
  def up_votes
    votes.where(vote: true).size
  end
  
  def down_votes
    votes.where(vote: false).size
  end

  def already_upvoted?(user)
    vote = votes.find_by(user_id: user.id, vote: true)
    vote.present? ? true : false
  end

  def already_downvoted?(user)
    vote = votes.find_by(user_id: user.id, vote: false)
    vote.present? ? true : false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update,
                                  :destroy, :vote]
  before_action :owned_post, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.active_friends.present? ||
       current_user.received_friends.present? ||
       current_user.present?
      active_users_ids = current_user.active_friends.pluck(:id)
      received_users_ids = current_user.received_friends.pluck(:id)
      user_ids = active_users_ids + received_users_ids + [current_user.id]
      @posts = Post.where(user_id: user_ids).order('created_at DESC')
      @posts.present? && respond_with(@posts)
    end
  end

  def show
    @comments = Comment.where(post_id: @post).order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post created!'
      respond_with(@post)
    else
      flash[:alert] =
        "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  def vote
    if !@post.already_upvoted?(current_user) && params[:vote] == 'true'
      vote = Vote.find_by(voteable: @post, creator: current_user, vote: false)
      if vote.present?
        vote.update_attributes(voteable: @post,
                               creator: current_user,
                               vote: params[:vote])
      else
        Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
      end
    elsif !@post.already_downvoted?(current_user) && params[:vote] == 'false'
      vote = Vote.find_by(voteable: @post, creator: current_user, vote: true)
      if vote.present?
        vote.update_attributes(voteable: @post,
                               creator: current_user,
                               vote: params[:vote])
      else
        Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
      end
    end
    redirect_to :back
  end

  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
%script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
.container
  .row
    = link_to 'New Post', new_post_path, class: 'btn btn-default stat-item'
    = link_to "Cancel", root_path, class: 'btn btn-default stat-item'
    -if @posts.present?
      - @posts.each do |post|
        .col-sm-8
          .panel.panel-white.post.panel-shadow
            .post-heading
              %h2=post.title
              .pull-left.image
                %img.img-circle.avatar{:alt => "user profile image", :src => "http://bootdey.com/img/Content/user_1.jpg"}/
            .post-description
              %p=truncate(post.body, length: 20)
              = link_to 'Show Post', post, class: 'btn btn-default stat-item'
              .stats
                %span.glyphicon.glyphicon-thumbs-up
                = link_to "Like", vote_post_path(post, vote: true), method: 'post'
                %span.glyphicon.glyphicon-thumbs-down
                = link_to "Unlike", vote_post_path(post, vote: false), method: 'post'
                - if current_user && post.user == current_user
                  = link_to 'Edit Post', edit_post_path(post), class: 'btn btn-default stat-item'
                  = link_to 'Destroy Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default stat-item'
            %p
              %span.glyphicon.glyphicon-user
              by #{post.user.name}
              |
              %span.glyphicon.glyphicon-calendar
              Posted #{time_ago_in_words(post.created_at)} ago.
              |
              %span.glyphicon.glyphicon-comment
              =pluralize(post.comments.count, "Comment")
              |
              %span.glyphicon.glyphicon-thumbs-up
              #{post.up_votes}
              %span.glyphicon.glyphicon-thumbs-down
              #{post.down_votes}


/ %table
/   %tr
/     %th Title
/     %th Body
/     %th Username

/   - @posts.each do |post|
/     %tr
/       %td= post.title
/       %td= post.body
/       %td= post.user.username
/       %td= link_to 'Show', post
/       %td
/         - if current_user && post.user == current_user
/           = link_to 'Edit', edit_post_path(post)
/       %td
/         - if current_user && post.user == current_user
/           = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

/       / %td= link_to 'Edit', edit_post_path(post)
/       / %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br
/ - if current_user
/   = link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
%script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
.container
  .well
    .media
      %a.pull-left{:href => "#"}
        %img.media-object{:src => "http://placekitten.com/150/150"}/
      .media-body
        %h2.media-heading=@post.title
        %p.text-right=@post.user.name
        %p=@post.body
        %ul.list-inline.list-unstyled
          %li
            %span
              %i.glyphicon.glyphicon-calendar
              %span.timestamp
                Posted #{time_ago_in_words(@post.created_at)} ago.
          %li |
          %span
            %i.glyphicon.glyphicon-comment
          =pluralize(@comments.count, "Comment")
          %li |
        / .stats
        /   %a.btn.btn-default.stat-item{:href => "#"}
        /     %i.fa.fa-thumbs-up.icon>
        /     = link_to "Like", like_post_path(@post), method: :put
        /   %a.btn.btn-default.stat-item{:href => "#"}
        /     %i.fa.fa-thumbs-down.icon>
        /     = link_to "Unlike", dislike_post_path(@post), method: :put
        - if @post.user.id == current_user.id
          .text-center.edit-links
            = link_to "Cancel", posts_path, class: 'btn btn-default stat-item'
            = link_to "Edit Post", edit_post_path(@post), class: 'btn btn-default stat-item'
        - else
          .text-center.edit-links
            =link_to "Cancel", posts_path, class: 'btn btn-default stat-item'
      =render 'comments/form'
      -  if @comments.present?
        = render 'comments/comment'


/ = link_to 'Edit', edit_post_path(@post)
/ \|
/ = link_to 'Back', posts_path
/ - if @post.user.id == current_user.id
/   .text-center.edit-links
/     = link_to "Cancel", posts_path
/     |
/     = link_to "Edit Post", edit_post_path(@post)
/ - else
/   .text-center.edit-links
/     =link_to "Cancel", posts_path
/ -  if @comments.present?
/   = render 'comments/comment'
/ - else
/   =render 'comments/form'