config/routes.rb
FacebookApp::Application.routes.draw do
  resources :users
  root to: 'home#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  resources :password_resets, only: [:new, :create, :edit, :update]
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'users/new'
  resources :posts do
    member do
      post 'vote'
    end
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  get 'friendships/create'
  get 'friendships/update'
  get 'friendships/destroy'
  resources :home
  resources :friendships, only: [:create, :update, :destroy]
end

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", home_index_path
          - if logged_in?
            %li= link_to "Users", '#'
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: "delete"
          - else
            %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FacebookApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield